# Custom Language File for Launcher Customizer

[ejs.app]
title = "World Of Glory Launcher | Stable"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaTiktokURL = "https://www.tiktok.com/@worldofglory.eu"
mediaDiscordURL = "https://discord.gg/FV6mwHVgam"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Dobrodošli na World Of Glory"
welcomeDescription = ""
welcomeDescCTA = "Započni svoju avanturu!"
