[ejs.landing]
updateAvailableTooltip = "Ažuriranje dostupno"
usernamePlaceholder = "Korisničko ime"
usernameEditButton = "Uredi"
settingsTooltip = "Podešavanja"
serverStatus = "SERVER"
serverStatusPlaceholder = "Van Mreže"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Usluge"
mojangStatusNETitle = "Nije esencijalno"
newsButton = "VESTI"
launchButton = "IGRAJ"
launchButtonPlaceholder = "• Nema odabrane veryije"
launchDetails = "Molimo pričekajte..."
newsNavigationStatus = "{currentPage} od {totalPages}"
newsErrorLoadSpan = "Provera vesti..."
newsErrorFailedSpan = "Neuspelo učitavanje vesti"
newsErrorRetryButton = "Pokušaj ponovno"
newsErrorNoneSpan = "Nema vesti"

[ejs.login]
loginCancelText = "Odustani"
loginSubheader = "PRIJAVA U MINECRAFT"
loginEmailError = "* Neispravna vrijednost"
loginEmailPlaceholder = "EMAIL ILI KORISNIČKO IME"
loginPasswordError = "* Obavezno polje"
loginPasswordPlaceholder = "LOZINKA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "zaboravljena lozinka?"
loginRememberMeText = "zapamti me?"
loginButtonText = "PRIJAVA"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Trebaš račun?"
loginPasswordDisclaimer1 = "Tvoja lozinka se šalje izravno Mojangu i nikada se ne pohranjuje."
loginPasswordDisclaimer2 = "{appName} nije povezan s Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Dobrodošli na NewEra RP"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Login with Mojang"
loginOptionCracked = "Prijava"
cancelButton = "Obustavi"

[ejs.overlay]
serverSelectHeader = "Dostupni Serveri"
serverSelectConfirm = "Odaberi"
serverSelectCancel = "Odustani"
accountSelectHeader = "Odaberi Karakter"
accountSelectConfirm = "Odaberi"
accountSelectCancel = "Odustani"

[ejs.settings]
navHeaderText = "Podešavanja"
navAccount = "Karakter"
navMinecraft = "Minecraft"
navMods = "Modovi"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "O nama"
navUpdates = "Ažuriranja"
navDone = "Gotovo"
tabAccountHeaderText = "Podešavanja Karaktera"
tabAccountHeaderDesc = "Dodaj nove karaktere ili upravljaj postojećima."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Dodaj Microsoft Račun"
mojangAccount = "Mojang"
crackedAccount = "Tvoji Karakteri"
addMojangAccount = "+ Dodaj Mojang Račun"
addCrackedAccount = "+ Dodaj Karakter"
minecraftTabHeaderText = "Podešavanja Minecraft-a"
minecraftTabHeaderDesc = "Opcije vezane za pokretanje igre."
gameResolutionTitle = "Rezolucija igre"
launchFullscreenTitle = "Pokreni u fullscreen-u."
autoConnectTitle = "Automatsko povezivanje na server pri pokretanju."
launchDetachedTitle = "Pokreni proces igre odvojeno od launcher-a."
launchDetachedDesc = "Ako igra nije odvojena, zatvaranje launcher-a zatvara igru."
tabModsHeaderText = "Podešavanja Modova"
tabModsHeaderDesc = "Omogući ili onemogući modove."
switchServerButton = "Promeni"
requiredMods = "Potrebni Modovi"
optionalMods = "Opcionalni Modovi"
dropinMods = "Drop-in Modovi"
addMods = "Dodaj Modove"
dropinRefreshNote = "(F5 za osvežavanje)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Omogući ili onemogući shadere. Napomena: Shaderi će raditi glatko samo na jakim mašinama. Ovde možete dodati prilagođene pakete."
selectShaderpack = "Odaberi Shaderpack"
tabJavaHeaderText = "Java Podešavanja"
tabJavaHeaderDesc = "Upravljanje konfiguracijom Java (napredno)."
memoryTitle = "Memorija"
maxRAM = "Maksimalni RAM"
minRAM = "Minimalni RAM"
memoryDesc = "Preporučeni minimalni RAM je 3 gigabajta. Postavljanje minimalne i maksimalne vrijednosti na istu vrednost može smanjiti zastajkivanje."
memoryTotalTitle = "Ukupno"
memoryAvailableTitle = "Dostupno"
javaExecutableTitle = "Java Izvršni Program"
javaExecSelDialogTitle = "Odaberi Java Izvršni Program"
javaExecSelButtonText = "Odaberi Datoteku"
javaExecDesc = "Java izvršni program se proverava pre pokretanja igre."
javaPathDesc = "Putanja bi se trebala završavati s <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Dodatne JVM Opcije"
jvmOptsDesc = "Opcije koje se pružaju JVM-u tokom izvršavanja. <em>-Xms</em> i <em>-Xmx</em> ne bi trebale biti uključene."
launcherTabHeaderText = "Podešavanja Launcher-a"
launcherTabHeaderDesc = "Opcije vezane za sami launcher."
allowPrereleaseTitle = "Dopusti Pre-Release Ažuriranja."
allowPrereleaseDesc = "Pre-Release uključuju nove funkcije koje možda nisu potpuno testirane ili integrisane.<br>Ovo će uvek biti isključeno ako koristite pre-release verziju."
dataDirectoryTitle = "Direktorijum Podataka"
selectDataDirectory = "Odaberi Direktorijum Podataka"
chooseFolder = "Odaberi Mapu"
dataDirectoryDesc = "Sve datoteke i lokalne instalacije Java-e biće sačuvane u direktorijumu podataka.<br>Snimci ekrana i svetovi će biti sačuvani u mapi instance za odgovarajuću konfiguraciju servera."
aboutTabHeaderText = "O Aplikaciji"
aboutTabHeaderDesc = "Pogledaj informacije i beleške o izdanju trenutne verzije."
aboutTitle = "{appName}"
stableRelease = "Stabilno Izdanje"
versionText = "Verzija "
sourceGithub = "Izvor (GitHub)"
support = "Source: HeliosLauncher | My Version available per Request (discord: ogidev) | Made with <3 by ogi"
devToolsConsole = "DevTools Konzola"
releaseNotes = "Beleške o Izdanju"
changelog = "Changelog"
noReleaseNotes = "Nema Beleški o Izdanju"
viewReleaseNotes = "Originalni Launcher"
launcherUpdatesHeaderText = "Ažuriranja Launcher-a"
launcherUpdatesHeaderDesc = "Preuzmi, instaliraj i pregledaj ažuriranja za launcher."
checkForUpdates = "Proveri Ažuriranja"
whatsNew = "Šta je novo"
updateReleaseNotes = "Beleške o Ažuriranju"

[ejs.waiting]
waitingText = "Čekanje na Microsoft.."

[ejs.welcome]
continueButton = "Nastavi"


[js.discord]
waiting = "Čekanje klijenta.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Prijava"
microsoftLogoutTitle = "Microsoft Odjava"

[js.login]
login = "PRIJAVA"
loggingIn = "PRIJAVA U TOKU"
success = "USPEŠNO"
tryAgain = "Pokušaj Ponovo"

[js.login.error]
invalidValue = "* Neispravna Vrednost"
requiredValue = "* Obavezno Polje"

[js.login.error.unknown]
title = "Nepoznata Greška Pri Prijavi"
desc = "Došlo je do nepoznate greške. Pogledajte konzolu za detalje."

[js.landing.launch]
pleaseWait = "Molimo sačekajte..."
failureTitle = "Greška Prilikom Pokretanja"
failureText = "Pogledajte konzolu (CTRL + Shift + i) za više detalja."
okay = "U redu"

[js.landing.selectedAccount]
noAccountSelected = "Nijedan izabrani karakter"

[js.landing.selectedServer]
noSelection = "Nijedan izabrani server"
loading = "Učitavanje.."

[js.landing.serverStatus]
server = "SERVER"
offline = "VAN MREŽE"
players = "IGRAČI"

[js.landing.systemScan]
checking = "Provera informacija o sistemu.."
noCompatibleJava = "Nije pronađena kompatibilna<br>instalacija Java-e"
installJavaMessage = "Da biste pokrenuli Minecraft, potrebna vam je 64-bitna instalacija Java-e {major}. Želite li da instaliramo kopiju?"
installJava = "Instaliraj Java-u"
installJavaManually = "Ručna Instalacija"
javaDownloadPrepare = "Priprema za preuzimanje Java-e.."
javaDownloadFailureTitle = "Greška prilikom preuzimanja Java-e"
javaDownloadFailureText = "Pogledajte konzolu (CTRL + Shift + i) za više detalja."
javaRequired = "Java je potrebna<br>za pokretanje"
javaRequiredMessage = 'Potrebna je važeća x64 instalacija Java-e {major} za pokretanje.<br><br>Obratite se našem <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Vodiču za upravljanje Java-om</a> za upute o ručnoj instalaciji Java-e.'
javaRequiredDismiss = "Razumem"
javaRequiredCancel = "Nazad"

[js.landing.downloadJava]
findJdkFailure = "Nije uspelo pronalaženje distribucije OpenJDK."
javaDownloadCorruptedError = "Preuzeta JDK ima loš heš, datoteka može biti oštećena."
extractingJava = "Raspakivanje Java-e"
javaInstalled = "Java instalirana!"

[js.landing.dlAsync]
loadingServerInfo = "Učitavanje informacija o serveru.."
fatalError = "Fatalna greška"
unableToLoadDistributionIndex = "Nije moguće učitati kopiju indeksa distribucije. Pogledajte konzolu (CTRL + Shift + i) za više detalja."
pleaseWait = "Molimo sačekajte.."
errorDuringLaunchTitle = "Greška prilikom pokretanja"
seeConsoleForDetails = "Pogledajte konzolu (CTRL + Shift + i) za više detalja."
validatingFileIntegrity = "Provera celovitosti datoteke.."
errorDuringFileVerificationTitle = "Greška prilikom provere datoteke"
downloadingFiles = "Preuzimanje datoteka.."
errorDuringFileDownloadTitle = "Greška prilikom preuzimanja datoteke"
preparingToLaunch = "Priprema za pokretanje.."
launchingGame = "Pokretanje igre.."
launchWrapperNotDownloaded = "Osnovna datoteka, LaunchWrapper, nije uspela pravilno da se preuzme. Kao rezultat toga, igra se ne može pokrenuti.<br><br>Da biste rešili ovaj problem, privremeno isključite antivirusni softver i ponovo pokrenite igru.<br><br>Ako imate vremena, molimo vas da <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">podnesete problem</a> i javite nam koji antivirusni softver koristite. Kontaktiraćemo ih i pokušati rešiti stvari."
doneEnjoyServer = "Gotovo. Uživajte u serveru!"
checkConsoleForDetails = "Molimo proverite konzolu (CTRL + Shift + i) za više detalja."

[js.landing.news]
checking = "Provera vesti"

[js.landing.discord]
loading = "Učitavanje igre.."
joining = "Ulazak u igru!"
joined = "Istraživanje Kraljevine!"

[js.overlay]
dismiss = "Odbaci"

[js.settings.fileSelectors]
executables = "Izvršne Datoteke"
allFiles = "Sve Datoteke"


[js.settings.mstfLogin]
errorTitle = "Došlo je do Greške"
errorMessage = "Microsoft autentikacija nije uspela. Molimo pokušajte ponovo."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Došlo je do Greške"
errorMessage = "Microsoft odjava nije uspela. Molimo pokušajte ponovo."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Izaberi Karakter"
selectedButton = "Izabrani Karakter ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Upozorenje<br>Ovo je Vaš Poslednji Karakter"
lastAccountWarningMessage = "Da biste koristili launcher, morate biti prijavljeni sa najmanje jednim karakterom. Moraćete se ponovo prijaviti nakon ovoga.<br><br>Da li ste sigurni da želite da se odjavite?"
confirmButton = "Siguran Sam"
cancelButton = "Otkaži"

[js.settings.authAccountPopulate]
username = "Korisničko Ime"
uuid = "UUID"
selectAccount = "Izaberi Karakter"
selectedAccount = "Izabrani Karakter ✓"
logout = "Odjavi se"

[js.settings.dropinMods]
removeButton = "Ukloni"
deleteFailedTitle = "Brisanje Drop-in Moda nije uspelo<br>{fullName}"
deleteFailedMessage = "Proverite da li se datoteka koristi i pokušajte ponovo."
failedToggleTitle = "Upravljanje jednim ili više Drop-in Modova nije uspelo"
okButton = "U redu"

[js.settings.serverListing]
mainServer = "Glavni Server"

[js.settings.java]
selectedJava = "Izabrano: Java {version} ({vendor})"
invalidSelection = "Nevažeći Izbor"
requiresJava = "Potrebna je Java {major} x64."
availableOptions = "Dostupne Opcije za Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stabilna Verzija"
releaseNotesFailed = "Nije uspelo učitavanje beleški o izdanju"

[js.settings.updates]
newReleaseTitle = "Dostupno Novo Izdanje"
newPreReleaseTitle = "Dostupan Novi Pre-release"
downloadingButton = "Preuzimanje.."
downloadButton = 'Preuzmi sa GitHub-a<span style="font-size: 10px;color: gray;text-shadow: none !important;">Zatvorite lanser i pokrenite dmg datoteku da biste ažurirali.</span>'
latestVersionTitle = "Koristite Najnoviju Verziju"
checkForUpdatesButton = "Proveri Ažuriranja"
checkingForUpdatesButton = "Provera Ažuriranja.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Fatalna Greška: Nemoguće Učitati Indeks Distribucije"
fatalErrorMessage = "Nije moguće uspostaviti vezu sa našim serverima kako bi preuzeli indeks distribucije. Nijedna lokalna kopija nije bila dostupna za učitavanje. <br><br>Indeks distribucije je esencijalna datoteka koja pruža najnovije informacije o serveru. Lanser ne može startovati bez nje. Proverite da li ste povezani s internetom i ponovo pokrenite aplikaciju."
closeButton = "Zatvori"

[js.uibinder.validateAccount]
failedMessageTitle = "Neuspeh Osvežavanja Prijave"
failedMessage = "Nismo mogli osvežiti prijavu za <strong>{account}</strong>. Molimo izaberite drugi karakter ili se ponovo prijavite."
failedMessageSelectAnotherAccount = "Nismo mogli osvežiti prijavu za <strong>{account}</strong>. Molimo prijavite se ponovo."
loginButton = "Prijava"
selectAnotherAccountButton = "Izaberi Drugi Karakter"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Provera Ažuriranja..."
installNowButton = "Instaliraj Sada"
checkForUpdatesButton = "Proveri Ažuriranja"
[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
